config/routes.rb
Rails.application.routes.draw do
  resources :homeworks
  resources :assignments
  resources :students
  resources :reconciliations

end

app/models/reconciliation.rb
class Reconciliation < ActiveRecord::Base
end

app/controllers/reconciliations_controller.rb
class ReconciliationsController < ApplicationController
  before_action :set_reconciliation, only: [:show, :edit, :update, :destroy]

  # GET /reconciliations
  # GET /reconciliations.json
  def index
    @logged_in_user = Student.find_by github_id: params[:github_id]
    @marked_incomplete = Assignment.includes(:homeworks).where(homeworks: { complete: false, student_id: @logged_in_user.id })
    @no_match = Assignment.includes(:homeworks).where(homeworks: { id: nil })
  end

  # GET /reconciliations/1
  # GET /reconciliations/1.json
  def show
  end

  # GET /reconciliations/new
  def new
    @reconciliation = Reconciliation.new
  end

  # GET /reconciliations/1/edit
  def edit
  end

  # POST /reconciliations
  # POST /reconciliations.json
  def create
    @reconciliation = Reconciliation.new(reconciliation_params)

    respond_to do |format|
      if @reconciliation.save
        format.html { redirect_to @reconciliation, notice: 'Reconciliation was successfully created.' }
        format.json { render :show, status: :created, location: @reconciliation }
      else
        format.html { render :new }
        format.json { render json: @reconciliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reconciliations/1
  # PATCH/PUT /reconciliations/1.json
  def update
    respond_to do |format|
      if @reconciliation.update(reconciliation_params)
        format.html { redirect_to @reconciliation, notice: 'Reconciliation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reconciliation }
      else
        format.html { render :edit }
        format.json { render json: @reconciliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reconciliations/1
  # DELETE /reconciliations/1.json
  def destroy
    @reconciliation.destroy
    respond_to do |format|
      format.html { redirect_to reconciliations_url, notice: 'Reconciliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reconciliation
      @reconciliation = Reconciliation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reconciliation_params
      params.require(:reconciliation).permit(:date_name)
    end
end

app/views/reconciliations/_form.html.erb
<%= form_for(@reconciliation) do |f| %>
  <% if @reconciliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reconciliation.errors.count, "error") %> prohibited this reconciliation from being saved:</h2>

      <ul>
      <% @reconciliation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_name %><br>
    <%= f.text_field :date_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reconciliations/edit.html.erb
<h1>Editing Reconciliation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reconciliation %> |
<%= link_to 'Back', reconciliations_path %>

app/views/reconciliations/index.html.erb
<!-- This content will display in the yield portion of layouts/application.html.erb -->
<div id="one">
    <p id="notice"><%= notice %></p>
    <button class= "btn" type="submit">Sign in with GitHub</button>

    <h1>GIT IT</h1>
    <h2 class="subhead">Homework Tracker</h2>

</div>

<div id="two">
  <div id="homework">
    <!-- Pulls in github_id to include in welcome statement -->
    <h2>Welcome, <%= params[:github_id] %></h2>
    <h3>Do your homework!</h3>
    <!-- Pulls information from the reconciliations controller -->
    <% @marked_incomplete.each do |assignment| %>
    <ul>
    <!-- Assignments are filtered based on completion and student from the reconciliations controller -->
      <li><%= assignment.homeworks.inspect %></li>
    </ul>
    <% end %>
    <!-- List each new assignment -->
    <% @no_match.each do |assignment| %>
    <ul>
      <li><%= assignment.homeworks.inspect %></li>
    </ul>
    <% end %>

  </div>
</div>

app/views/reconciliations/new.html.erb
<h1>New Reconciliation</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/reconciliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date name:</strong>
  <%= @assignment.date_name %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>