config/routes.rb
Rails.application.routes.draw do
  resources :homeworks
  resources :assignments
  resources :students
  resources :reconciliations

end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :student
  belongs_to :assignment
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:complete, :student_id, :assignment_id)
    end
end

app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :assignment_id %><br>
    <%= f.text_field :assignment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Complete</th>
      <th>Student</th>
      <th>Assignment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.complete %></td>
        <td><%= homework.student %></td>
        <td><%= homework.assignment %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Complete:</strong>
  <%= @homework.complete %>
</p>

<p>
  <strong>Student:</strong>
  <%= @homework.student %>
</p>

<p>
  <strong>Assignment:</strong>
  <%= @homework.assignment %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>